import { z } from "zod";

// Agent Schema
export const agentSchema = z.object({
  id: z.coerce.string(),
  firstName: z.string().min(1, { message: "First name is required!" }),
  lastName: z.string().min(1, { message: "Last name is required!" }),
  email: z
    .string()
    .email({ message: "Invalid email address!" })
    .min(1, { message: "Email is required!" }),
  userName: z
    .string()
    .min(3, { message: "Username must be at least 3 characters long!" })
    .max(20, { message: "Username must be at most 20 characters long!" }),
  password: z
    .string()
    .min(8, { message: "Password must be at least 8 characters long!" })
    .or(z.literal("")),

  officeAddress: z.string().min(1, { message: "Office Address is required!" }),
  homeAddress: z.string().min(1, { message: "Home Address is required!" }),
  city: z.string().min(1, { message: "City is required!" }),


  ContactNumber1: z.string().min(1, { message: "Contact Number 1 is required!" }),
  ContactNumber2: z.string().optional().or(z.literal("")), 
});

export type AgentSchema = z.infer<typeof agentSchema>;



//Staff Schema
export const staffSchema = z.object({
  id: z.coerce.string().optional(),
  firstName: z.string().min(1, { message: "First name is required!" }),
  lastName: z.string().min(1, { message: "Last name is required!" }),
  email: z
    .string()
    .email({ message: "Invalid email address!" })
    .min(1, { message: "Email is required!" }),
  userName: z
    .string()
    .min(3, { message: "Username must be at least 3 characters long!" })
    .max(20, { message: "Username must be at most 20 characters long!" }),
  password: z
    .string()
    .min(8, { message: "Password must be at least 8 characters long!" })
    .optional()
    .or(z.literal("")), 
  section: z.string().optional().or(z.literal("")), 
  superviserID: z.string().optional().or(z.literal("")),
});

export type StaffSchema = z.infer<typeof staffSchema>;



export const lotterySchema = z.object({
  LotteryID: z.coerce.number().int().optional(), // Optional because it's auto-generated by Prisma
  StaffID: z.string().min(1, { message: "Staff ID is required!" }),
  LotteryName: z.string().min(1, { message: "Lottery Name is required!" }),
  Availability: z.string().min(1, { message: "Stock Availability Name is required!" }),
  LotteryType: z.string().min(1, { message: "Lottery Type is required! (eg: NLB , DLB or instance)" }),
  ImageUrl: z.string().min(1, { message: "Image Link is required!" }),
  DrawDate: z.coerce.date().refine(date => {
    const today = new Date();
    today.setHours(0, 0, 0, 0); 
    return date >= today;
  }, { message: "Draw Date must be today or in the future!" }),
    UnitPrice: z.coerce.number().positive({ message: "Unit Price must be a positive number!" }),
  UnitCommission: z.coerce.number().positive({ message: "Unit Commission must be a positive number!" }),
  LastUpdateDate: z.coerce.date().optional().default(() => new Date()), // Defaults to current date if not provided
});

export type LotterySchema = z.infer<typeof lotterySchema>;



// url({ message: "Invalid image URL!" }).min(1, { message: "Image URL is required!" })